### ISSUE TITLE
aiwaz Command Has a Bug

### ISSUE THREAD

**Issue by ChisanaKita** [ChisanaKita/AIWAZ#6]
since I using "moment-timezone"， client.readyAt now return the current time instead the ready_At time object. 
> ## Suggest :
> - Remove The Function.
> - Move This Function To Other Command.
> - Stop Using "moment-timezone" And Calculate The Return Object To HK Time

**Comment by XiaoBeiLab** [comment]
Try switch to const read_At = client.readyAt; And put in outside the main function

**Comment by ChisanaKita** [comment]
# Problem Fixed
See [f1931a5](https://github.com/ChisanaKita/AIWAZ/commit/f1931a5299c747ae27a3238e1b4e6db6411a2341) For More Information
